[package]
name = "bullets_on_wheels"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[[bin]]
path = "src/run_godot.rs"
name = "bullets_on_wheels"

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
  "bevy_state",
  "bevy_asset",
  "bevy_log",
  "gamepad",
] }
godot = "0.4"
godot-bevy = { version = "0.11.0", features = ["default"] }
bevy_rapier2d = "0.33.0"
rand = "0.9.2"
glam = "0.30.9"
test-case = "3.3.1"
enum_delegate = "0.2.0"
cargo-godot-lib = "0.2.0"
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[build-dependencies]
image = "0.25.7"
imageproc = "0.24"


[features]
itest = []
