direction: right

"CharacterDeathMessage": { shape: page }
"CharacterHitMessage": { shape: page }
"CreateEnemyMessage": { shape: page }
"EnemySpawnedMessage": { shape: page }
"MouseButtonInput": { shape: page }
"MouseMotion": { shape: page }
"SceneTreeMessage": { shape: page }
"ShootMessage": { shape: page }

"character_bullet_collision_system": { shape: rectangle }
"emit_level_loaded_event_when_scene_ready": { shape: rectangle }
"gamepad_input": { shape: rectangle }
"handle_character_zero_health_system": { shape: rectangle }
"handle_mouse_motion_system": { shape: rectangle }
"handle_mouse_system": { shape: rectangle }
"on_shoot_message_system": { shape: rectangle }
"score_tracker": { shape: rectangle }
"shoot_at_player_system": { shape: rectangle }
"shoot_virtual_joystick": { shape: rectangle }
"spawn_enemies_after_time": { shape: rectangle }
"spawn_enemy_health_bar": { shape: rectangle }
"spawn_enemy_system": { shape: rectangle }
"update_healthbar_animation_system": { shape: rectangle }

"character_bullet_collision_system" -> "CharacterDeathMessage": writes
"character_bullet_collision_system" -> "CharacterHitMessage": writes
"SceneTreeMessage" -> "emit_level_loaded_event_when_scene_ready": reads
"gamepad_input" -> "ShootMessage": writes
"CharacterDeathMessage" -> "handle_character_zero_health_system": reads
"MouseMotion" -> "handle_mouse_motion_system": reads
"MouseButtonInput" -> "handle_mouse_system": reads
"handle_mouse_system" -> "ShootMessage": writes
"ShootMessage" -> "on_shoot_message_system": reads
"CharacterDeathMessage" -> "score_tracker": reads
"shoot_at_player_system" -> "ShootMessage": writes
"shoot_virtual_joystick" -> "ShootMessage": writes
"spawn_enemies_after_time" -> "CreateEnemyMessage": writes
"EnemySpawnedMessage" -> "spawn_enemy_health_bar": reads
"CreateEnemyMessage" -> "spawn_enemy_system": reads
"CharacterHitMessage" -> "update_healthbar_animation_system": reads
